# Generated by Django 2.2.4 on 2019-12-16 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_district_center', models.BooleanField(default=False)),
                ('is_region_center', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('in_process', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_id', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ManyToManyField(related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkerEstimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(default=0)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Marker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='marker_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Region'),
        ),
    ]
