# Generated by Django 2.2.4 on 2019-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
    ]
