# Generated by Django 2.2.4 on 2019-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190820_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
    ]
