# Generated by Django 2.2.4 on 2019-08-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20190829_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='short_description',
        ),
    ]
