# Generated by Django 2.2.4 on 2019-08-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20190826_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='short_description',
        ),
    ]
