# Generated by Django 2.2.4 on 2019-08-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_remove_marker_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='long_description',
            new_name='description',
        ),
    ]
