# Generated by Django 2.2.4 on 2019-08-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20190829_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='marker_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Region', unique=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
