# Generated by Django 2.2.4 on 2019-08-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20190829_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.TextField(default='No description given', max_length=1000),
        ),
        migrations.AlterField(
            model_name='marker',
            name='marker_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Region'),
        ),
    ]
