# Generated by Django 2.2.4 on 2019-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20190827_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
