# Generated by Django 2.2.4 on 2019-08-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_marker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
