# Generated by Django 2.2.4 on 2019-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20190829_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', null=True, upload_to='images/'),
        ),
    ]
