# Generated by Django 2.2.4 on 2019-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20190829_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(default='image/None/no-img.jpg', upload_to='image/'),
        ),
    ]
