# Generated by Django 2.2.4 on 2019-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_auto_20190830_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
