# Generated by Django 2.2.4 on 2019-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20190830_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
