# Generated by Django 2.2.4 on 2019-08-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_auto_20190830_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(height_field='100', upload_to='images/', width_field='100'),
        ),
    ]
