# Generated by Django 2.2.4 on 2019-09-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20190829_1152'),
        ('map', '0030_auto_20190830_2303'),
    ]

    operations = [

    ]
