# Generated by Django 2.2.4 on 2019-09-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0031_merge_20190904_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
