# Generated by Django 2.2.4 on 2019-09-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20190829_1152'),
        ('map', '0031_auto_20190830_2304'),
    ]

    operations = [
    ]
