# Generated by Django 2.2.4 on 2019-09-15 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0031_merge_20190915_0306'),
    ]

    operations = [

    ]
