# Generated by Django 2.2.4 on 2019-09-15 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0032_auto_20190915_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='follower',
            field=models.ManyToManyField(related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
