# Generated by Django 2.2.4 on 2019-09-04 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_auto_20190904_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
