# Generated by Django 2.2.4 on 2019-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_merge_20190901_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='isCluster',
            field=models.BooleanField(default=0),
        ),
    ]
