# Generated by Django 2.2.4 on 2019-09-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_marker_iscluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='isCluster',
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
    ]
