# Generated by Django 2.2.4 on 2019-09-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20190904_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='creator',
        ),
    ]
