# Generated by Django 2.2.4 on 2019-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_auto_20190901_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
