# Generated by Django 2.2.4 on 2019-09-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_city_district_town_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
        migrations.RemoveField(
            model_name='town',
            name='city',
        ),
    ]
