# Generated by Django 2.2.4 on 2019-09-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_auto_20190914_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='town',
        ),
    ]
