# Generated by Django 2.2.4 on 2019-09-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_remove_village_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.District'),
        ),
        migrations.AddField(
            model_name='town',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.District'),
        ),
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.District'),
        ),
    ]
