# Generated by Django 2.2.4 on 2019-09-15 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_auto_20190914_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
    ]
