# Generated by Django 2.2.4 on 2019-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190831_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile_images/default-avatar.png', upload_to='images/profile_images'),
        ),
    ]
