"""
Django settings for uapp project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&_5unbomung3$+3g1ukpn-!0xuc$yd1#k_32k5!za0szc6j^(b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'map',
    'authorization',
    'dashboard',
    'django.contrib.sites',
    'bootstrap_modal_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'bootstrap4',
    'fancybox',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Directories where the engine should look for template source files, in search order.
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'django.template.context_processors.media'
            ],
            'loaders':[
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
            'libraries': {
                'custom_tags': 'uapp.templatetags.custom_tags'
            },
        },
    },
]

WSGI_APPLICATION = 'uapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'UbaL7ybB1a',
        'NAME': 'UbaL7ybB1a',
        'PASSWORD': 'Dc8JaMqq0r',
        'HOST': 'remotemysql.com',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "map/static"),
    os.path.join(BASE_DIR, "dashboard/static")
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AVATAR = 'images/profile_images/default-avatar.png'

# Enable the default site framework
SITE_ID = 1

# App Common Information
SITE_SHORT_NAME = 'uapp'
APP_EMAIL_FROM = 'support@uapp.com'
APP_URL_TOP_LOGO = BASE_DIR + 'static/images/logo.png'
BASE_URL = '127.0.0.1:8000'

# Custom Password settings
MIN_PASS_LENGTH = 8
PASSWORD_RESET_TIMEOUT_DAYS = 1

# User Login Options
LOGIN_URL = '/auth/login/'
LOGOUT_URL = '/auth/logout/'
LOGIN_REDIRECT_URL = '/'

# Google reCAPTCHA v3 api keys
GRECAP_SITE_KEY = '6LckjbQUAAAAAEx09GT7Blw04WGQjPTJWmvv-eKx'
GRECAP_SECRET_KEY = '6LckjbQUAAAAAMbTcoRK9Yav1nQhvbV5mWGbl70A'

GRECAP_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'

# SMTP Server Settings

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'uapp.confirmation@gmail.com'
EMAIL_HOST_PASSWORD = 'dmytroanddmytro2001'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# SMTP for Production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

AUTH_PROFILE_MODULE = "authorization.UserProfile"